### PR TITLE
Crosslink nx alanvgreen

### PR DESCRIPTION
**Pull request by alanvgreen**
A grab bag of changes. The first three are good to go. The rest are WIP and/or temporary.

### CODE REVIEW

**Comment by davidcorrigan714** [comment]
Is your part really an 8 speed grade? Mine's a 9 and that's what's listed in the user manual.

For the clock constraint I had more problems including it than not. With the internal oscillator block it was smart enough to figure things out properly, otherwise it seems like the tooling complains with the constraint applied to the net instead of a pin. My thought is to do a switch argument to demo multiple clocking options, so that with the template someone can see how to use the PLL and an external pin, but not have to set that jumper on the first go. Unfortunately for the UART output they really have to either do some soldering or attach another UART adapter to a PMOD.

I'm also planning to make a board for the FMC port to demo some of the chips I'm planning to use, namely an ethernet chip and some extra flash. If there's anything else worth trying out I'm all for adding other things to the board. I was thinking some RAM would be interesting so I could try and get Linux booting on it, but not sure the trace routing will really allow for it.

**Comment by alanvgreen** [comment]
1. Yes, the part number on mine is "LIFCL-40 8BG400CES". I just found that my colleague's board is a 9 like yours, so I'll drop that commit. There's clearly something odd about the board that I have.

2. I'd really like to have clock constaints, particularly when starting to push designs a little closer to their limits. Let's revisit once the PLL is done.

3. IIRC, you said you had added the resistors to enable the UART? How is that working? Do they interfere with the I2C? On Ubuntu, there's some messiness with the way Lattice deals with the /dev filesystem such that an external USB UART is pretty desirable. 

4.  Someone got Linux up on the hackaday badge, using [this SDRAM cartridge](https://hackaday.io/project/168591-hadbadge-2019-sdram-cartridge) as well as the onboard QSPI PSRAM. If DDR won't work, there are other, more forgiving options.

**Comment by tcal-x** [comment]
I too have a LIFCL-40 8BG400CES (10232H10).

**Comment by alanvgreen** [comment]
I moved the RAM and ROM change up, since @tcal-x has tested loading programs

**Comment by davidcorrigan714** [comment]
1. Since there's some -8s floating around seems like it'd be fine just to leave at -8 which should work fine on both.

2. I'll do some more testing in a bit with some of my updates to the OSCA. I realized later that the divisor was off by one so I wonder if it was having extra problems with conflicting constraints between what it expected and the constraint I had at the time.

3. I took off all the I2C resistors (R18 - R21) so it's just a straight shot from the FPGA to the FTDI and no more I2C for my board.

4. Looks interesting. When I get around to laying out my board I'll take a look at RAM options, want to get this all upstreamed first. Antmicro got a quad core running on an Arty and I think the FPGA is similar in size so that might be a fun diversion & demo to put up.

**Pull request merged**
